// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clzhqyjpnfvfauqlbwqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsemhxeWpwbmZ2ZmF1cWxid3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MjQxNzAsImV4cCI6MjA1NjQwMDE3MH0.OxVxaQojDeyUzmhbbXRn5CjsU4Xb1QqfDof6TkO2DFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);